/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package datos;

/**
 *
 * @author alumno
 */
public class DEPARTAMENTOCRUD extends javax.swing.JFrame {

    /**
     * Creates new form DEPARTAMENTOCRUD
     */
    public DEPARTAMENTOCRUD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        it = new javax.swing.JLabel();
        conta = new javax.swing.JLabel();
        rrhh = new javax.swing.JLabel();
        marke = new javax.swing.JLabel();
        produc = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();
        agreit = new javax.swing.JTextField();
        agreconta = new javax.swing.JTextField();
        agrerrhh = new javax.swing.JTextField();
        agremarke = new javax.swing.JTextField();
        agreprodu = new javax.swing.JTextField();
        agregar = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DEPARTAMENTO");

        it.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        it.setText("IT: ");

        conta.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        conta.setText("Contabilidad:");

        rrhh.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rrhh.setText("RRHH:");

        marke.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        marke.setText("Marketing: ");

        produc.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        produc.setText("Produccion");

        menu.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        menu.setText("MENU");

        agreit.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        agreconta.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        agreconta.setToolTipText("");

        agrerrhh.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        agremarke.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        agreprodu.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        agregar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        agregar.setText("AGREGAR");

        actualizar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        actualizar.setText("ACTUALIZAR");

        eliminar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        eliminar.setText("ELIMINAR");

        limpiar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        limpiar.setText("LIMIPIAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(it)
                            .addComponent(conta)
                            .addComponent(rrhh))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(marke)
                            .addGap(11, 11, 11)))
                    .addComponent(produc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agreconta)
                    .addComponent(agrerrhh)
                    .addComponent(agreprodu, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(agremarke)
                    .addComponent(agreit, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(140, 140, 140))
            .addGroup(layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agregar)
                    .addComponent(eliminar))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(actualizar)
                    .addComponent(limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(150, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menu)
                .addGap(280, 280, 280))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(menu)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(it)
                    .addComponent(agreit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conta)
                    .addComponent(agreconta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rrhh)
                    .addComponent(agrerrhh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marke)
                    .addComponent(agremarke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(produc)
                    .addComponent(agreprodu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregar)
                    .addComponent(actualizar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eliminar)
                    .addComponent(limpiar))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DEPARTAMENTOCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DEPARTAMENTOCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DEPARTAMENTOCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DEPARTAMENTOCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DEPARTAMENTOCRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JTextField agreconta;
    private javax.swing.JButton agregar;
    private javax.swing.JTextField agreit;
    private javax.swing.JTextField agremarke;
    private javax.swing.JTextField agreprodu;
    private javax.swing.JTextField agrerrhh;
    private javax.swing.JLabel conta;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel it;
    private javax.swing.JButton limpiar;
    private javax.swing.JLabel marke;
    private javax.swing.JLabel menu;
    private javax.swing.JLabel produc;
    private javax.swing.JLabel rrhh;
    // End of variables declaration//GEN-END:variables
}
